<?php // $Id$
/*
      +----------------------------------------------------------------------+
      | CLAROLINE version 1.5.*                              |
      +----------------------------------------------------------------------+
      | Copyright (c) 2001, 2004 Universite catholique de Louvain (UCL)      |
      +----------------------------------------------------------------------+
      |   $Id$               |
      |   English Translation                                                |
      +----------------------------------------------------------------------+

      +----------------------------------------------------------------------+
      | Translator :                                                         |
      |          Xavier de Pedro   <xavidp@confluencia.net>                  |
      +----------------------------------------------------------------------+
 */
// help_forums.php

$langHFor="Ajuda de Fòrums";
$langClose="Tanca finestra";

$langForContent="El fòrum és una eina de discussió asíncrona i escrita.
 Si el correu-e permet diàleg un-a-un, els fòrums permeten diàleg públic o
 semi-public.</p><p>Tècnicament parlant, els estudiants necessiten només el seu 
 navegador per emprar els fòrums de claroline.</P><p>Per organitzar fòrums, punxa 
 sobre 'Administra'. Les discussions són organitzades en conjunts i subconjunts 
 com segueix:</p><p><b>Categoria > Fòrum > Tòpic > Respostes</b></p>Per estructurar 
 les discussions dels teus estudiants, és necessari organitzar categories i 
 fòrums a priori, deixant la cració de tòpics i respostes a ells. Per 
 defecte, el fòrum de claroline conté només la categoria 'Public', un fòrum 
 d'exemple i un tòpic d'exemple.</p><p>La primera cosa que hauries de fer és esborrar
 el tòpic d'exemple i modificar el nom del primer fòrum. Llavors, pots crear, 
 en la categoria 'public', altres fòrums, per grups o per temes, per adjustar-se 
 als requeriments del teu escenari d'aprenentatge.</p><p>No barregis Categories i 
 fòrums, i no oblidis que una categoria buida (sense fòrums) no apareix en la plana 
 que veuen els estudiants.</p><p>La descripció d'un fòrum pot ser la llista dels 
 seus membres, la definició d'un objectiu, una tasca, un tema...";



// help_home.php

$langHHome="Ajuda de Plana d'Inici";
$langHomeContent="Per major conveniència, les eines de claroline contenen entrades per 
 defecte. Hi ha un exemple petit en cada eina per ajudar a que agafis més ràpid com 
 funciona. Depèn de tu el modificar l'exemple o esborrar-lo.</p><p> Per exemple,
 aquí a la Plana d'Inici del lloc web del teu curs, hi ha una petit text 
 introductori dient 'Aquest és el text introductori del teu curs. Per substituir-lo
 pel teu propi text, punxa sota sobre modificar.' Punxa sobre modificar, edita-ho 
 i d'acord. És així de simple. Cada eina té la mateixa llògica: afegeix, esborra, 
 modifica, que és la llògica de llocs web dinàmics.</p><p>Quan crees per primera 
 vegada el lloc web del teu curs, la majoria de les eines es troben actives. Aquí 
 de nou, depèn de tu que desactivis les que no necessites. Només cal que punxis 
 sobre 'desactivar'. Llavors se'n va abaix a la secció gris de la teva plana inicial
 i es torna invisible als teus estudiants.  No obstant, pots reactivar-ho 
 quan vulguis, fent-ho visible als estudiants un cop més.</p>
<p>Pots afegir les teves pròpies planes a la teva Plana d'Inici. Aquestes 
 planes han de ser planes HTML (que poden ser creades per qualsevol processador 
 de textos o editor Web). Utilitza 'Puja imatge i enllaça a Plana d'Inici' per 
 enviar la teva plana al servidor. La capçalera estàndar del teu lloc web serà
 automàticament fusionada amb el teu nou document, de tal forma que només necessites 
 concentrar-te en el contingut. Si vols enllaçar des de l'Inici cap a 
 llocs web existents o planes existents en qualsevol part de la xarxa (inclús dins el 
 teu propi lloc), utilitza 'Afegeix enllaç a Plana d'Inici'. Les planes que has afegit
 a la Plana d'Inici poden ser desactivades i llavors són esborrades, mentres les eines
 estàndar poden ser desactivades, però no esborrades.</p><p>Un cop el lloc web del teu
 curs està preparat, ves a 'Modifica info del curs' i decideix quin nivell de
 confidencialitat vols. Per defcte, el teu curs és amagat (per que treballes en ell).</p>";



// help_claroline.php

$langHClar="Ajuda d'Inici";


$langClarContent="Aquí, professors i assistents creen i administren
 llocs web de cursos. Els estudiants llegeixen (documents, agendes, informacions) i, 
 alguns cops, fan exercicis, publiquen treballs, participen a les discussions de 
 fòrums...</p><b>Enregistrament</b><p>Les següents instruccions només 
 s'apliquen si la teva versió de claroline permet auto-enregistrament (alguns llocs 
 t'enregistren automaticament). <br>Si ets un estudiant, només necessites 
 enregistrar-te seleccionant 'Segueix cursos (estudiant)', llavors escull
 els cursos que voldries seguir.</p><p>Si ets un Professor o un Assistent, 
 enregistrat igualment, però selecciona 'Crea cursos (professor)'. Llavors hauràs 
 d'omplir un formulari amb el Codi del Curs, Facultat i Títol del Curs. Un cop això 
 validat, seràs dirigit al lloc web que acabes de crear i podràs modificar el seu 
 contingut i organització d'acord amb els teus requeriments. </p><p>La opció 'Per fer' 
 és per permetre retroalimentació per als administradors del teu lloc web claroline.  
 Les coses que podries enviar aquí inclouen faltes o suggeriments per millores. La 
 llista 'Per fer' es troba enllaçada a la Plana Inicial del campus (un cop entrat).</p>
<p>El fòrum de suport és diferent. Conecta tots els usuaris de Claroline arreu del món.
Si no trobes la resposta a la pregunta dins el teu campus claroline i voltants, 
deixa un missatge allà.</p>
<p>L'enllaç a Enregistrament (si existeix) és a la Plana d'Inici del campus 
 (dalt dreta).</p><b>Accés</b><p>A les teves properes visites, tecleja usuari/paraula de pas
 i D'acord per accedir als teus cursos. L'adreça URL del lloc és";
$langClarContent3="</p><p><b>Teoria Educacional</b><p>Per als professors,
 preparar un curs sobre internet és una qüestió de Teoria Educacional també.";
$langClarContent4="és a la teva disposició ajudar-te durant els diferents passos 
 de l'evolució del teu projecte d'ensenyament: des del disseny de la eina a la seva 
 integració en una estratègia clara i coherent, i avaluació objectiva del seu 
 impacte sobre l'aprenentatge de l'estudiant.</p>";



// help_document.php

$langHDoc="Ajuda de Documents";

$langDocContent="<p>L'eina de Documents és similar a l'Administrador d'arxius del 
 teu ordinador de sobretaula.</p><p>POts pujar fitxers de qualsevol tipus (HTML, Word,
 Powerpoint, Excel, Acrobat, Flash, Quicktime, etc.). La teva única preocupació 
 ha de ser que els teus alumnes tinguin el software apropiat per llegir-los.
 Alguns tipus de fitxers poden contenir virus, és la teva responsabilitat no pujar 
 fitxers contaminats de virus. Val la pena la precaució de comprovar els documents amb 
 programari antivirus abans de pujar-los.</p>
<p>Els documents són presentats en ordre alfabètic.<br><b>Nota : </b>Si vols 
 presentar-los en un ordre diferent, numera'ls: 01, 02,
 03...</p>
<p>Pots :</p>
<h4>Pujar un document</h4>
<ul>
  <li>Selecciona el fitxer en el teu ordinador emprant el butó Busca<input
 type=submit value=Busca name=submit2>
	a la dreta de la teva pantalla.</li>
		<li>
			Inicia la pujada amb el Botó Puja <input type=submit value=Puja name=submit2>.
		</li>
	</ul>
	<h4>
		Reanomena un document (o un directori)
	</h4>
	<ul>
		<li>
			punxa sobre el <img src=../document/img/edit.gif width=20 height=20 align=baseline> 
			botó sobre la columna Reanomena
		</li>
		<li>
			Tecleja el nom nou en el camp (dalt esquerra)
		</li>
		<li>
			Valida en punxar <input type=submit value=D'acord name=submit24>.
		</li>
	</ul>
		<h4>
			Esborra un document (o un directori)
		</h4>
		<ul>
			<li>
				Punxa sobre <img src=../document/img/delete.gif width=20 height=20> 
				a la columna 'Esborra'.
			</li>
		</ul>
		<h4>
			Fer un document (o directori) invisible als estudiants
		</h4>
		<ul>
			<li>
				Punxa sobre <img src=../document/img/visible.gif width=20 height=20>
				a la columna 'Visible/invisible'.
			</li>
			<li>
				El document (o directori) encara existeix, però ja no és visible pels estudiants.
			</li>
			<li>
				Per fer-lo invisible de nou, punxa sobre 
				<img src=../document/../document/img/invisible.gif width=24 height=20> 
				a la columna 'Visible/invisible'
			</li>
		</ul>
		<h4>
			Afegeix o modifica un comentari a un document (o a un directori)
		</h4>
		<ul>
			<li>
				Punxa sobre <img src=../document/../document/img/comment.gif width=20 height=20> a la columna 'Comenta'
			</li>
			<li>
				Escriu el nou comentari a el corresponent camp (dalt dreta).
			</li>
			<li>
				Valida-ho en punxar sobre <input type=submit value=D'acord name=submit2>
			.</li>
		</ul>
		<p>
		Per esborrar un comentari, punxa sobre <img src=../document/../document/img/comment.gif width=20 height=20>, 
		esborra el comentari vell en el camp i punxa sobre
		<input type=submit value=D'acord name=submit22>.
		<hr>
		<p>
			Pots organitzar el teu contingut en omplir-ho . Per a això:
		</p>
		<h4>
			<b>
				Crea un directori 
			</b>
		</h4>
		<ul>
			<li>
				Punxa sobre 
				<img src=../document/../document/img/dossier.gif width=20 height=20>
				'Crea un directori' (dalt esquerra)
			</li>
			<li>
				Escriu el nom del teu nou directori al corresponenet camp (dalt esquerra)
			</li>
			<li>
				Valida-ho en punxar sobre <input type=submit value=D'acord name=submit23>.
			</li>
		</ul>
		<h4>
			Mou un document (o directori)
		</h4>
		<ul>
			<li>
				Punxa sobre el botó <img src=../document/../document/img/deplacer.gif width=34 height=16> 
				a la columna 'Mou'
			</li>
			<li>
				Escull el directori cap al qual vols moure el document (o directori) in el menu desplegable corresponent (dalt esquerra) (nota: la paraula 'arrel' vol dir que no pots anar més amunt que el nivell de l'arbre de documents del servidor).
			</li>
			<li>
				Valida-ho en punxar sobre <input type=submit value=D'acord name=submit232>.
			</li>
		</ul>
<center>
<p>";




// Help_user.php

$langHUser="Ajuda d'Usuaris";
$langUserContent="<b>Roles</b><p>Els rols no tenen funció relacionada amb l'ordinador.
 No donen drets sobre el sistema operatiu. Només indiquen als humans,
 qui és qui. Pots modificar-los en punxar sobre 'modifica' sota 
 'rol', llavors escriure el que vulguis: professor, assistent, estudiant,
 visitant, expert...</P><hr>
<b>Drets d'administrador</b>
<p>Els drets d'administrador, per altra banda, corresponen a l'autorització tècnica per  
 modifiocar el contingut i organització del lloc web del curs.
 Fins el moment, només pots escollir entre donar tots els drets d'aministració 
 i no donar-ne cap.</P>
<p>Per permetre a un assistent, per exemple, que co-administri el lloc, necessites 
 enregistrar-lo en el curs o assegurar-te que ja es troba enregistrat, llavors punxar 
 sobre 'modifica' sota 'drets d'admin', llavors punxas sobre 'tots', llavors 'D'acord'.</P><hr>
<b>Co-chairmen</b>
<p>Per esmentar en la capçalera del lloc web del curs el nom d'un 
 co-chairmen, utilitza l'eina 'Modifica informació del curs' (eines taronja). Aquesta 
 modificació no enregistra el teu co-chairmen com un usuari del curs.
 El camp 'Professors' és completament independent de la llista d'Usuaris.</p><hr>
<b>Afegeix un usuari</b>
<p>Per afegir un usuari per al teu curs, omple els camps i valida. La persona 
rebrà un correu-e dient-li que l'has enregistrat/da i dient-li 
o recordant-li el seu nom d'usuari/a i el seu/seva paraula de pas.</p>";

// Help Group

$langGroupManagement="Ajuda de Grups";
$langGroupContent="<p><b>Introducció</b></p>
<p>Aquesta eina permet crear i gestionar grups de treball. 
En ser creats (Crea grups), els grups es troben buits. Hi ha moltes 
maneres d'omplir-los:
<ul><li>automaticament ('Omple grups'),</li>
<li>manualment ('Edita'),</li>
<li>auto-enregistrament pels estudiants (Opció de Grups: 'Auto enregistrament permès...').</li>
</ul>
Aquestes tres maneres poden ser combinades. Pots, per exemple, demanar als estudiants
que s'autoenregistrin primer. Llavors descobrir que alguns d'ells no ho van fer i 
decidir llavors omplir grups automaticament de cara a completar-los. També pots editar 
cada grup per assignar un estudiant cada vegada a un grup abans o després de
l'autoenregistrament i/o omplert automàtic.</p>
<p>Omplert de grups, sigui automàtic o manual, funciona només si ja hi ha estudiants 
enregistrats en el curs (no barregis enregistrament en el curs amb enregistrament en grups).
La llista d'estudiants és visible a través de l'eina <b>Usuaris</b>. </p><hr noshade size=1>
<p><b>Crea grups</b></p>
<p>Per crear grups nous, punxa sobre 'Crea nou grup(s)' i determina el nombre de grups a ser creats. El màxim nombre de membres és opcional però nosaltres suggerim d'escolir-ne un. Si
deixes el camp max. sense canvis, la mida màxima dels grups serà infinita.</p><hr noshade size=1>
<p><b>Especificacions dels Grups</b></p>
<p>Pots determinar les especificacions dels Grups de forma global (per tots els grups).
<b>Els estudiants es poden autoenregistrar en grups</b>: 
<p>Crees grups buits, els estudiants s'autoenregistren. 
Si has definit un nombre màxim, els grups plens no accepten nous membres. Aquest mètode 
és bo per professors que no coneixen la llista d'estudiants quan creen els grups .</p>
<b>Utilitats</b>:</p>
<p>Cada grup posseeix un fòrum (privat or públic) o un Àrea de Documents 
(un administrador de fitxers compartit) o (el més freqüent) ambdós.</p>
<hr noshade size=1>
<p><b>Edició manual</b></p>
<p>Un cop s'han creat els grups (Crea grups), veus a la part baixa de la plana, una llista de 
grups amb una sèrie d'informacions i funcions 
<ul><li><b>Edita</b> per modificar manualment el nom del grup, descripció, tutor, 
llistat de membres.</li>
<li><b>Esborra</b> esborra un grup.</li></ul>
<hr noshade size=1>";
?>