<?php // $Id$
/*
      +----------------------------------------------------------------------+
      | CLAROLINE version 1.5.*                              |
      +----------------------------------------------------------------------+
      | Copyright (c) 2001, 2004 Universite catholique de Louvain (UCL)      |
      +----------------------------------------------------------------------+
      |   $Id$       |
      |   English Translation                                                |
      +----------------------------------------------------------------------+

      +----------------------------------------------------------------------+
      | Translator :                                                         |
      |          Xavier de Pedro   <xavidp@confluencia.net>                  |
      +----------------------------------------------------------------------+
 */
$langModify="modifica";
$langDelete="esborra";
$langTitle="Títol";
$langHelp="Ajuda";
$langOk="D'acord";
$langAddIntro="Afegeix text introductori";
$langBackList="Retorna a la llista";
$langMaj="Actualitza";



// exercice.php

$langExercices="Exercicis";
$langEvalSet="Especificacions de la puntuació";
$langExercice="Exercici";
$langActive="actiu";
$langInactive="inactiu";
$langActivate="activa";
$langDeactivate="desactiva";
$langNoEx="No hi ha exercici fins el moment";
$langNewEx="Nou exercici";


// exercice_admin.php

$langQuestCreate="Creació de preguntes";
$langExRecord="El teu exercici ha estat guardat";
$langBackModif="Retorna a editar aquest exercici";
$langDoEx="Fes l'exercici";
$langDefScor="Defineix les especificacions de la puntuació";
$langCreateModif="Creació/modificació de preguntes";
$langSub="Subtítol";
$langNewQu="Nova pregunta";
$langQuestion="Pregunta";
$langQuestions="Preguntes";
$langDescription="Descripció";
$langAnswers="Respostes";
$langTrue="Veritat";
$langAnswer="Resposta";
$langComment="Comentari";
$langMorA="+resp.";
$langLesA="-resp.";
$langRecEx="Guarda exercici";
$langRecQu="Guuarda pregunta";
$langRecAns="Guarda respostes";
$langIntroduction="Introducció";
$langTitleAssistant="Assitent de creació d'exercicis";
$langQuesList="Llistat de preguntes";
$langSaveEx="Guarda exercici";
$langClose="Tanca";
$langFinish="Finalitza";
$langCancel="Cancel·la";
$langQImage="Pregunta-dibuix";
$langAddQ="Afegeix pregunta";

// exercice_submit.php

$langDoAnEx="Fes un exercici";
$langGenerator="generador d'exercicis";
$langResult="Puntuació";
$langChoice="La teva elecció";
$langCorrect="Veritat";



// scoring.php & scoring_student.php

$langPossAnsw="nombre de possibles respostes per una pregunta";
$langStudAnsw="nombre d'errors fets per l'estudiant";
$langDetermine="Determina tu mateix el pes de la puntuació a través d'editar la taula de sota. Punxa llavors sobre \"D'acord\"";
$langNonNumber="Un valor no numèric en";
$langAnd="i"; 
$langReplaced="ha estat introduït. Ha estat reemplaçat per 0";
$langSuperior="Un valor més gran que 20 a";
$langRep20="ha estat introduït. Ha estat reemplaçat per 20";
$langDefault="Valors per defecte *";
$langDefComment="* Si punxes sobre \"Valors per defecte\", els teus valors antics seran permanentment esborrats.";
$langScoreGet="Números en negre = Puntuació";


$langShowScor="Mostra la puntuació als estudiants : "; 







?>
