<?php // $Id$
/*
      +----------------------------------------------------------------------+
      | CLAROLINE version 1.5.*                                |
      +----------------------------------------------------------------------+
      | Copyright (c) 2001, 2004 Universite catholique de Louvain (UCL)      |
      +----------------------------------------------------------------------+
      |   $Id$           |
	  |   English Translation                                                |
      +----------------------------------------------------------------------+

      +----------------------------------------------------------------------+
      | Translator :                                                         |
      |          Xavier de Pedro   <xavidp@confluencia.net>                  |
      +----------------------------------------------------------------------+
 */
// forum_admin.inc

$langForums="Forums";
$langOrganisation="Forums administration";
$langForCat="Forums of the category";
$langBackCat="Back to categories";
$langForName="Forum name";
$langDescription="Description";
$langFunctions="Functions";
$langAddForCat="Add forum into category";
$langAdd="add";
$langChangeCat="Change of category";
$langSave="Save";
$langModCatName="Modify category name";
$langCat="Category";
$langNameCat="Category name has been modified";
$langBack="Back";
$langCatAdded="Category added";
$langForCategories="Forum categories";
$langAddForums="To add forums,click on \"Forums\" in the category of your choice. An empty category (without forums) won't be visible for students";
$langCategories="Categories";
$langNbFor="Number of forums";
$langFunctions="Functions";
$langAddCategory="Add a category";

?>
