<?php // $Id$
/*
      +----------------------------------------------------------------------+
      | CLAROLINE version 1.5.*                                |
      +----------------------------------------------------------------------+
      | Copyright (c) 2001, 2004 Universite catholique de Louvain (UCL)      |
      +----------------------------------------------------------------------+
      |   $Id$           |
	  |   English Translation                                                |
      +----------------------------------------------------------------------+

      +----------------------------------------------------------------------+
      | Translator :                                                         |
      |          Xavier de Pedro   <xavidp@confluencia.net>                  |
      +----------------------------------------------------------------------+
 */
$langModify="Modifica";
$langDelete="Esborra";
$langTitle="Títol";
$langHelp="Ajuda";
$langOk="D'acord";
$langAddIntro="Afegeix text d'introducció";
$langBackList="Retorna a la llista";




// WORKS
$langDownloadFile="Puja document";
$langTooBig="No has escollit cap fitxer o el fitxer és massa gran.";
$langListDeleted="La llista sencera ha estat esborrada.";
$langDocModif="títol del treball modificat";
$langDocAdd="Treball afegit";
$langDocDel="Treball esborrat";
$langTitleWork="Títol del treball";
$langAuthors="Autors";
$langDescription="Descripció del treball";
$langDelList="Esborra la llista sencera";

$langWorks="Treballs dels estudiants";

$langDocument = "Document";




?>
