<?php // $Id$
/*
      +----------------------------------------------------------------------+
      | CLAROLINE version 1.5.*                              |
      +----------------------------------------------------------------------+
      | Copyright (c) 2001, 2004 Universite catholique de Louvain (UCL)      |
      +----------------------------------------------------------------------+
      |   $Id$              |
      |   Italian translation                                                |
      +----------------------------------------------------------------------+

      +----------------------------------------------------------------------+
      | Translator:                                                          |
      +----------------------------------------------------------------------+
 */

// GENERIC

$langModify="modificare";
$langDelete="cancellare";
$langTitle="Titolo";
$langHelp="Aiuto";
$langOk="confermare";
$langAddIntro="Aggiungere un testo di introduzione";
$langBackList="Ritorno all'elenco";


// AGENDA

$langAgenda="Agenda";
$langDay="Giorno";
$langHour="Ora";
$langLasting="Durata";

$langMonth="Mese"; 
$langYear="Anno"; 
$langMinute ="Minuti"; 

$langAddEvent="Aggiungere un evento";
$langDetail="Dettagli";
$month_default="mese";
$january="gennaio";
$february="febbraio";
$march="marzo";
$april="aprile";
$may="maggio";
$june="giugno";
$july="luglio";
$august="agosto";
$september="settembre";
$october="ottobre";
$november="novembre";
$december="dicembre";
$year_default="anno";
$year1="2001";
$year2="2002";
$year3="2003";
$hour_default="Ora";

$langOldToNew = "Invertire"; 
$langNewToOld = "Invertire"; 
$langNow = "Ora"; 


$langSETLOCALE="ITALIAN";  
// UNIX TIME SETTINGS, "15h00" instead of "3pm", for instance, "ENGLISH" is a possibility


?>
