ALTER IGNORE TABLE `cours` ADD `diskQuota` int(10) unsigned AFTER `departmentUrl`;
ALTER IGNORE TABLE `cours` ADD `creationDate` DATETIME AFTER `lastEdit` ;
ALTER IGNORE TABLE `cours` CHANGE `diskQuota` `diskQuota` int(10) unsigned ;
ALTER IGNORE TABLE `cours` CHANGE `lastVisit` `lastVisit` DATETIME DEFAULT NULL;
ALTER IGNORE TABLE `cours` CHANGE `expirationDate` `expirationDate` DATETIME DEFAULT NULL;
ALTER IGNORE TABLE `cours` CHANGE `creationDate` `creationDate` DATETIME DEFAULT NULL;
ALTER IGNORE TABLE `cours` CHANGE `lastEdit` `lastEdit` DATETIME DEFAULT NULL;
UPDATE `cours` SET `lastVisit` = NULL WHERE `lastVisit` = '0000-00-00 00:00:00';
UPDATE `cours` SET `expirationDate` = NULL WHERE `expirationDate` = '0000-00-00 00:00:00';
UPDATE `cours` SET `creationDate` = NULL WHERE `creationDate` = '0000-00-00 00:00:00';
UPDATE `cours` SET `lastEdit` = NULL WHERE `lastEdit` = '0000-00-00 00:00:00';
