<?php
/*
      +----------------------------------------------------------------------+
      | CLAROLINE version 1.3.0 $Revision$                             |
      +----------------------------------------------------------------------+
      | Copyright (c) 2001, 2002 Universite catholique de Louvain (UCL)      |
      +----------------------------------------------------------------------+
      |   $Id$              |
      |   Italian translation                                                |
      +----------------------------------------------------------------------+
      |   This program is free software; you can redistribute it and/or      |
      |   modify it under the terms of the GNU General Public License        |
      |   as published by the Free Software Foundation; either version 2     |
      |   of the License, or (at your option) any later version.             |
      |                                                                      |
      |   This program is distributed in the hope that it will be useful,    |
      |   but WITHOUT ANY WARRANTY; without even the implied warranty of     |
      |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      |
      |   GNU General Public License for more details.                       |
      |                                                                      |
      |   You should have received a copy of the GNU General Public License  |
      |   along with this program; if not, write to the Free Software        |
      |   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA          |
      |   02111-1307, USA. The GNU GPL license is also available through     |
      |   the world-wide-web at http://www.gnu.org/copyleft/gpl.html         |
      +----------------------------------------------------------------------+
      | Authors: Thomas Depraetere <depraetere@ipm.ucl.ac.be>                |
      |          Hugues Peeters    <peeters@ipm.ucl.ac.be>                   |
      |          Christophe Gesché <gesche@ipm.ucl.ac.be>                    |
      +----------------------------------------------------------------------+
      | Translator:                                                          |
      +----------------------------------------------------------------------+
 */

// GENERIC

$langModify="modificare";
$langDelete="cancellare";
$langTitle="Titolo";
$langHelp="Aiuto";
$langOk="confermare";
$langAddIntro="Aggiungere un testo di introduzione";
$langBackList="Ritorno all'elenco";


// AGENDA

$langAgenda="Agenda";
$langDay="Giorno";
$langHour="Ora";
$langLasting="Durata";

$langMonth="Mese"; 
$langYear="Anno"; 
$langMinute ="Minuti"; 

$langAddEvent="Aggiungere un evento";
$langDetail="Dettagli";
$month_default="mese";
$january="gennaio";
$february="febbraio";
$march="marzo";
$april="aprile";
$may="maggio";
$june="giugno";
$july="luglio";
$august="agosto";
$september="settembre";
$october="ottobre";
$november="novembre";
$december="dicembre";
$year_default="anno";
$year1="2001";
$year2="2002";
$year3="2003";
$hour_default="Ora";

$langOldToNew = "Invertire"; 
$langNewToOld = "Invertire"; 
$langNow = "Ora"; 


$langSETLOCALE="ITALIAN";  
// UNIX TIME SETTINGS, "15h00" instead of "3pm", for instance, "ENGLISH" is a possibility


?>
